### ISSUE TITLE
Use Global Variable instead of InfoBlock

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/Asylum-API#11]
- Previously we were reading the scanner sensitivities from the "InfoBlock" with the command td_ReadValue("XLVDT Sens"). The cypher has a Sensitivity that depends on the sample height, as discussed in the document.
- Instead we should read the sensitivity from the "Global Variable" with the command GV("XLVDTSens") (this needs to be done every time the tip motor changes - it may be possible to use a callback from Igor to notify LabVIEW when it changes, but this is not necessary)
- The change to GV() will work for both the Cypher and MFP3D (the InfoBlock method only worked for MFP3D)

More discussion here:
- [Cypher_LVDT_Sample_Height_Compensation-1.pdf](https://github.com/levylabpitt/AFM-Lithography/files/11557827/Cypher_LVDT_Sample_Height_Compensation-1.pdf)
- [Asana Discussion](https://app.asana.com/0/1361169047879/1204502516123216)

**Comment by ciozi137** [comment]
Confusingly, GV() means "Get Value" and reads the value from the Global Variable Table.

**Comment by ciozi137** [comment]
@Monkeymerlot I'm working on this. Just wanted you to be aware

**Comment by Monkeymerlot** [comment]
OK it should be really easy to make the change. You should be able to only change "Asylum_Driver_GetLVDTParameters.vi" as this is the only place that is calling the X(Y)LVDT parameters that was causing the issue. It would be best build a unit testable "build" function that ensures the proper format of the string before it gets sent to the Igor API if you wanted to be consistent with the rest of the driver. The tests are in the Asylum Driver Project.

**Comment by ciozi137** [comment]
Hi @Monkeymerlot correct that is where the LVDT parameters are retrieved. However it's a little more complicated because I can't just change Build Read Value because it appears that td_ReadValue is still needed in some other places, OR the names in the tables are similar but slightly different.
For example:
- `td_ReadValue("XLVDT Sense")` ✔️ 
- `GV("XLVDT Sens")` ☹️
- `GV("XLVDTSense")` ✔️ [no space!]

**Comment by Monkeymerlot** [comment]
I was thinking that you would make a new functionality called "GetValue" and then use the GV(...) like I do with the td_readvalue, and then replace that in the VI I mentioned above.

**Comment by ciozi137** [comment]
@Monkeymerlot yes exactly

**Comment by Monkeymerlot** [comment]
Check out https://github.com/levylabpitt/Asylum-API/tree/GetValue

**Comment by ciozi137** [comment]
This look great thanks

**Comment by Monkeymerlot** [comment]
> `GV("XLVDT Sens")` ☹️

Did you try `GV("XLVDTSens")` ie no `e` at the end as well? That is what is listed in the master variables table : 
![image](https://github.com/levylabpitt/Asylum-API/assets/37567672/e7ff67e9-96ac-4a75-87b2-aac3c50500be)
