### ISSUE TITLE
Igor-API?

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/Asylum-API#5]
I would like to reuse some of this code for making and modifying Igor graphs (the basic Igor functionality). Does it makes sense to break out the Igor-related part of this project into its own repository/package? And then make Asylum-API depend on "Igor-API".

Relevant VIs:
![image](https://user-images.githubusercontent.com/26659428/234574289-f1725cf4-1dc3-4041-b72e-0b097d5e1386.png)

**Comment by ciozi137** [comment]
LV-Data has a class to create Igor commands, which then get inserted into Igor Text Files (*.itx):
![image](https://user-images.githubusercontent.com/26659428/234578933-8afab1cb-cf2b-4cac-9de0-fb26d1b938da.png)
These functions also belong inside an "Igor-API" package...they can be used inside an ITX file or they can be sent directly to Igor via the ActiveX node.

**Comment by Monkeymerlot** [comment]
I think it would make sense. At the time it didn't make sense to make a totally new package for just a few functions that I was only using for a single purpose.
________________________________

**Comment by ciozi137** [comment]
**Igor-API v1.0.0.1**
