### ISSUE TITLE
EnsureIgorStringFormat Icon

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/Asylum-API#7]
Make icon more space efficient?
![image](https://user-images.githubusercontent.com/26659428/234576613-5dd1d058-54cd-4f50-b884-42347be19704.png)

to:
![image](https://user-images.githubusercontent.com/26659428/234576955-fb0d0636-58ea-4ee5-953a-0d9091a08b2d.png)

I don't think error wire data flow is necessary for this function. I view this VI as a special case of "trim whitespace":
![image](https://user-images.githubusercontent.com/26659428/234577883-a61b1df4-32ee-4fb6-b235-67d94b74e9fe.png)

**Comment by Monkeymerlot** [comment]
I'm not at my computer at the moment, but this looks good as long as there doesn't need to be an error wire into the functions.
________________________________

**Comment by ciozi137** [comment]
**Igor-API v1.0.0.1**
