### ISSUE TITLE
Load Data

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/Asylum-API#9]
These VIs should be part of "Igor-API". At the very least they should be part of "Asylum-API", not part of Lithography package.
![image](https://user-images.githubusercontent.com/26659428/234583580-c2be013c-bfa8-4f16-8e62-3dec50591a1c.png)

**Comment by ciozi137** [comment]
In the litho repository dev branch I deleted these in preparation for the new Igor VI

**Comment by ciozi137** [comment]
@Monkeymerlot I will try to repackage and push to the package repo 2pm. No name changes, just change the packaging and dependencies

**Comment by Monkeymerlot** [comment]
@ciozi137  No worries I was just going to look at these VIs to make sure that they really belonged in the Igor repo or not, but I think they all do.

**Comment by ciozi137** [comment]
@Monkeymerlot I got side tracked...gonna work on this now. And re: name changes, Asylum_OpenRefnum --> Igor_OpenRefnum and similar

**Comment by ciozi137** [comment]
**Igor-API v1.0.0.1**
